PROJECT_NAME = ParkingTicketFare
SOURCE = main.c 
CC = gcc
PROJECT_OUTPUT = $(PROJECT_NAME).out
build: $(SOURCE)
gcc $(SOURCE) -o $(PROJECT_OUTPUT)

run:$(PROJECT_OUTPUT)
./$(PROJECT_OUTPUT)

clean:
rm *.out

doc: 
make -C documentation
